<a href="https://colab.research.google.com/github/alanapooler827/554Homework7/blob/main/ST554_HW6_Pooler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Author: Alana Pooler
<br>
Purpose: Complete Homework 7

The purpose of this homework is to practice fitting MLR and logistic regression models (including penalized or regularized models). We will use the wine quality data set from the UCI Machine Learning Repository.

Input variables (based on physicochemical tests)

* fixed acidity
* volatile acidity
* citric acid
* residual sugar
* chlorides
* free sulfur dioxide
* total sulfur dioxide
* density
* pH
* sulphates
* alcohol


Output variable (based on sensory data): quality (score between 0 and 10)

Rather than try to predict quality, let's make our target variable for fitting multiple linear regression type models alcohol.

For fitting logistic regression type models we'll use the type of wine as the response variable.

First import some packages we will need throughout the notebook.

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression, LassoCV, Lasso

### Read in wine data sets

Read in the red wine data set and view the first few rows

In [2]:
red = pd.read_csv('winequality-red.csv', sep=';')
red.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

Read in the white wine data set and view the first few rows

In [4]:
white = pd.read_csv('winequality-white.csv', sep=';')
white.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

Before combining the two data sets together, we will add a 'type' column to each to label the wines as 'red' and 'white

In [ ]:
red['type'] = 'red'
white['type'] = 'white'

Now we will combine the two data sets together and view the first few rows of the new data set.

In [6]:
wine = pd.concat([red, white])
wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

### Split the Data

Now we need to split up the data set into a training and test set. We will use stratified sampling to make sure that there is a similar proportion of white and red wines in the training and test sets.

We will use 80% of the data for the training set and 20% of the data for the test set.

In [ ]:
df_train, df_test = train_test_split(
    wine,
    test_size=0.2,
    stratify=wine['type'],
    random_state=42
)

# create X and Y train sets for regression
y_train_reg = df_train['alcohol']
X_train_reg = df_train.drop(columns=['alcohol', 'type'])

# create X and Y test sets for regression
y_test_reg = df_test['alcohol']
X_test_reg = df_test.drop(columns=['alcohol', 'type'])

## Regression Task

We will train several regression models - multiple linear regression, LASSO, ridge regression, and elastic net. For every model, we will use 'alcohol' as the response variable.

First, we will fit four different multiple linear regression models and use CV to select the best one.
* At least one should include interaction terms
* At least one should include some polynomial terms (you may want to standardize your predictors
but that is up to you)
* Use CV to select your best MLR model

The first MLR model will be a simple

Fit a LASSO model with a set of predictors of your choosing
* Use at least five predictors
* Use CV to select the tuning parameter

Fit a Ridge Regression model with a set of predictors of your choosing
* Use at least five predictors
* Use CV to select the tuning parameter

Fit an Elastic Net model with a set of predictors of your choosing
* Use at least five predictors
* Use CV to select the tuning parameters

## Classification Task

In [ ]:
# create X and Y train sets for classification
y_train_clf = (df_train['wine'] == 'white').astype(int)
X_train_clf = df_train.drop(columns=['wine'])

# create X and Y test sets for classification
y_test_clf = (df_test['wine'] == 'white').astype(int)
X_test_clf = df_test.drop(columns=['wine'])